
title: Jonathan Tannen
email: jonathan.tannen@gmail.com
description: ""
baseurl: "" 
url: "https://jtannen.github.io"
twitter_username: jtannen215
github_username: jtannen

# Build settings
theme: minima
plugins:
  - jekyll-feed

header_pages:
  - research.md
  - teaching.md
  - about.md

